import jsPDF from 'jspdf';

interface SelectionForPdf {
  id: string;
  external_id: string;
  title: string;
  thumbnail: string;
  note: string;
  category: string;
  resolution: string;
  duration: string;
}

// Convert image URL to base64
async function imageToBase64(url: string): Promise<string | null> {
  try {
    const response = await fetch(url);
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

export async function generateSelectionsPdf(selections: SelectionForPdf[]): Promise<string> {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  
  // Header
  pdf.setFillColor(245, 158, 11); // Amber color
  pdf.rect(0, 0, pageWidth, 35, 'F');
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Looks Collection', margin, 22);
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`${selections.length} clips selected • ${new Date().toLocaleDateString()}`, margin, 30);
  
  let yPosition = 50;
  const thumbnailWidth = 45;
  const thumbnailHeight = 25;
  const rowHeight = 40;

  for (let i = 0; i < selections.length; i++) {
    const selection = selections[i];
    
    // Check if we need a new page
    if (yPosition + rowHeight > pdf.internal.pageSize.getHeight() - 20) {
      pdf.addPage();
      yPosition = 20;
    }

    // Try to load and add thumbnail
    const base64Image = await imageToBase64(selection.thumbnail);
    if (base64Image) {
      try {
        pdf.addImage(base64Image, 'JPEG', margin, yPosition, thumbnailWidth, thumbnailHeight);
      } catch {
        // Draw placeholder if image fails
        pdf.setFillColor(240, 240, 240);
        pdf.rect(margin, yPosition, thumbnailWidth, thumbnailHeight, 'F');
        pdf.setTextColor(150, 150, 150);
        pdf.setFontSize(8);
        pdf.text('No preview', margin + 10, yPosition + 14);
      }
    } else {
      // Draw placeholder
      pdf.setFillColor(240, 240, 240);
      pdf.rect(margin, yPosition, thumbnailWidth, thumbnailHeight, 'F');
      pdf.setTextColor(150, 150, 150);
      pdf.setFontSize(8);
      pdf.text('No preview', margin + 10, yPosition + 14);
    }

    // Title and details
    const textX = margin + thumbnailWidth + 8;
    
    pdf.setTextColor(30, 30, 30);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    
    // Truncate title if too long
    const maxTitleWidth = contentWidth - thumbnailWidth - 10;
    let title = selection.title;
    while (pdf.getTextWidth(title) > maxTitleWidth && title.length > 0) {
      title = title.slice(0, -1);
    }
    if (title !== selection.title) title += '...';
    
    pdf.text(title, textX, yPosition + 6);

    // Metadata
    pdf.setTextColor(100, 100, 100);
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`${selection.resolution} • ${selection.duration} • ${selection.category}`, textX, yPosition + 13);

    // Note
    if (selection.note) {
      pdf.setTextColor(80, 80, 80);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'italic');
      
      // Wrap note text
      const noteLines = pdf.splitTextToSize(`Note: ${selection.note}`, maxTitleWidth);
      pdf.text(noteLines.slice(0, 2), textX, yPosition + 20);
    }

    yPosition += rowHeight;
  }

  // Footer on last page
  const footerY = pdf.internal.pageSize.getHeight() - 10;
  pdf.setTextColor(150, 150, 150);
  pdf.setFontSize(8);
  pdf.text('Generated by Looks Collection', margin, footerY);
  pdf.text(`Page ${pdf.internal.pages.length - 1}`, pageWidth - margin - 15, footerY);

  // Return base64 without the data URI prefix
  const pdfBase64 = pdf.output('datauristring');
  return pdfBase64.split(',')[1];
}
