project_id = "rszawchsbpsmtrtvljta"

[functions.send-selections-pdf]
verify_jwt = false

[functions.notify-upload]
verify_jwt = false

[functions.notify-admin-signup]
verify_jwt = false

[functions.approve-user]
verify_jwt = false

[functions.generate-cover-images]
verify_jwt = false

[functions.analyze-circleback]
verify_jwt = false

[functions.scrape-creative-gallery]
verify_jwt = false

[functions.notify-proposal-signed]
verify_jwt = false

[functions.fetch-ical]
verify_jwt = false