project_id = "rszawchsbpsmtrtvljta"

[functions.send-selections-pdf]
verify_jwt = false

[functions.notify-upload]
verify_jwt = false

[functions.notify-admin-signup]
verify_jwt = false

[functions.approve-user]
verify_jwt = false